import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import localFont from 'next/font/local';

import './globals.css';

// const inter = Inter({ subsets: ['latin'] });

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko' className={`${pretendard.variable} `}>
      <body>{children}</body>
    </html>
  );
}
